<?php
return [
    'page_format'           => 'A4',
    'page_orientation'      => 'P',
    'page_units'            => 'mm',
    'unicode'               => true,
    'encoding'              => 'UTF-8',
    'font_directory'        => '',
    'image_directory'       => '',
    'tcpdf_throw_exception' => false,
    'use_fpdi'              => false,
    'use_original_header'   => true,
    'use_original_footer'   => true,
    'pdfa'                  => false, 
    'margin_header'       => '0',
    'margin_footer'       => '0',
    'margin_top'          => '15.24',
    'margin_bottom'       => '15.24',
    'margin_left'         => '12.7',
    'margin_right'        => '12.7',
];
